main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('campaign/<campaign_id>/', views.campaign, name='campaign'),    
    path('upload/<frame_id>/<campaign_id>', views.upload, name='upload'),
    path('quiz/<campaign_id>', views.quiz, name='quiz'),
    path('<country_code>/<language_code>/', views.index, name='index'),
]

pillow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from storages.backends.s3boto3 import S3Boto3Storage

class HomePage(models.Model):
    country_code = models.CharField(max_length=10, blank=False, default='in')
    language_code = models.CharField(max_length=10, blank=False, default='en')
    title = models.CharField(max_length=150, 
                                blank=True, default='',
                                verbose_name="HomePage Title", 
                                help_text="Bold text on first page user land -hero-section")

    description = models.TextField(max_length=350, 
                                blank=False, default='',
                                verbose_name="HomePage Description", 
                                help_text="description will display on home page below Title -hero-section")

    background = models.ImageField(default='d.png', 
                                upload_to='home',
                                verbose_name="Home page main banner",
                                help_text="Background Image for home page hero-section")

    def __str__(self):
        return f'{self.title}'

class Campaign(models.Model):
    homepage = models.ForeignKey(HomePage, on_delete = models.CASCADE, 
                                    blank=True,
                                    related_name="campaign", 
                                    verbose_name="homepage",
                                    help_text="select the home page within wich these campaign will be displayed.")

    title = models.CharField(max_length=150, 
                                blank=False, default='',
                                verbose_name="Campaign Title", 
                                help_text="eg. Entrepreneurs, Mentors")

    description = models.TextField(max_length=350, 
                                blank=False, default='',
                                verbose_name="Campaign Description", 
                                help_text="description will display on home page")

    commitment_section_title = models.CharField(max_length=150, 
                                blank=False, default='',
                                verbose_name="Campaign Sub Title", 
                                help_text="eg. make a commitment to yourself")

    commitment_section_description = models.TextField(max_length=350, 
                                blank=False, default='',
                                verbose_name="Campaign Sub Description", 
                                help_text="eg. Select the frame and create your custom image to share with the world.")

    icon = models.ImageField(default='d.png', 
                                upload_to='Campaign',
                                verbose_name="choose icon for Campaign",
                                help_text="icon will display on home page")
    
    background = models.ImageField(default='d.png', 
                                upload_to='Campaign',
                                verbose_name="background banner image for Campaign",
                                help_text="icon will display on home page")

    cta = models.CharField(max_length=150, 
                                blank=False, default='',
                                verbose_name="Call to action button name", 
                                help_text="This will be the button name on home page")

    def __str__(self):
        return f'{self.title}'


class Merged(models.Model):
    m_img = models.ImageField(default='d.png', upload_to='merged_pic')
    name = models.CharField(max_length=50, blank=False, default='')
    number = models.CharField(max_length=10, blank=False, default='')

    def __str__(self):
        return f'{self.id} merged'

class PrintName(models.Model):
    font_size = models.IntegerField(blank=False, default=25, 
                                        verbose_name='font size',
                                        help_text='font size to print name on image')

    x = models.IntegerField(blank=False, default=47, 
                                        verbose_name='x coordinate',
                                        help_text='x coordinate to print name on image, it helps to decide position')

    y = models.IntegerField(blank=False, default=634, 
                                        verbose_name='y coordinate',
                                        help_text='y coordinate to print name on image, it helps to decide position')

    def __str__(self):
        return  f"font size-{str(self.font_size)} x-{str(self.x)} y-{str(self.y)}"

class PrintDesignation(models.Model):
    font_size = models.IntegerField(blank=False, default=20, 
                                        verbose_name='font size',
                                        help_text='font size to print designation on image')

    x = models.IntegerField(blank=False, default=47, 
                                        verbose_name='x coordinate',
                                        help_text='x coordinate to print designation on image, it helps to decide position')

    y = models.IntegerField(blank=False, default=677, 
                                        verbose_name='y coordinate',
                                        help_text='y coordinate to print designation on image, it helps to decide position')

    def __str__(self):
        return  f"font size-{str(self.font_size)} x-{str(self.x)} y-{str(self.y)}"

class PrintCommitment(models.Model):
    font_size = models.IntegerField(blank=False, default=27, 
                                        verbose_name='font size',
                                        help_text='font size to print commitment on image')

    x = models.IntegerField(blank=False, default=714, 
                                        verbose_name='x coordinate',
                                        help_text='x coordinate to print commitment on image, it helps to decide position')

    y = models.IntegerField(blank=False, default=634, 
                                        verbose_name='y coordinate',
                                        help_text='y coordinate to print commitment on image, it helps to decide position')

    def __str__(self):
        return  f"font size-{str(self.font_size)} x-{str(self.x)} y-{str(self.y)}"

class PrintImage(models.Model):
    x = models.IntegerField(blank=False, default=369, 
                                        verbose_name='x coordinate',
                                        help_text='x coordinate to print photo on image, it helps to decide position')

    y = models.IntegerField(blank=False, default=669, 
                                        verbose_name='y coordinate',
                                        help_text='y coordinate to print photo on image, it helps to decide position')

    def __str__(self):
        return  f"x-{str(self.x)} y-{str(self.y)}"

class Userinfo(models.Model):
    name = models.CharField(max_length=40, blank=False, default='Name',
                                verbose_name="Form name field")
    email = models.EmailField(blank=True, 
                                verbose_name="Form email field")
    designation = models.CharField(max_length=40, blank=False, default=' ',
                                verbose_name="Form designation field")
    company_name = models.CharField(max_length=40, blank=False, default=' ',
                                verbose_name="Form Company name field")
    commitment = models.CharField(max_length=40, blank=False, default='Name',
                                verbose_name="Form Company name field")

class Frame(models.Model):
    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    # user_info = models.ForeignKey(Userinfo, on_delete=models.CASCADE)
    frame = models.ImageField(default='d.png', upload_to='frames_pic')
    mask = models.ImageField(default='d.png', upload_to='mask_img')
    frame_heading = models.CharField(max_length=150, blank=False, default='')
    frame_desc = models.CharField(max_length=350, blank=False, default='')
    page_title = models.CharField(max_length=150, blank=False, default='')
    page_desc = models.CharField(max_length=350, blank=False, default='')
    cta = models.CharField(max_length=150, blank=False, default='',
                                verbose_name="Call to action button name", 
                                help_text="This will display under frame image")
    print_name = models.ForeignKey(PrintName, on_delete=models.CASCADE)
    print_designation = models.ForeignKey(PrintDesignation, on_delete=models.CASCADE)
    print_commitment = models.ForeignKey(PrintCommitment, on_delete=models.CASCADE)
    print_image = models.ForeignKey(PrintImage, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.id} frame'

class Uimg(models.Model):
    img = models.ImageField(default='d.png', upload_to='user_img')

    def __str__(self):
        return f'{self.id} user pic'

class Question(models.Model):
    campaign = models.ForeignKey(
                Campaign, 
                related_name="questions", 
                on_delete = models.CASCADE)

    question = models.CharField(max_length=200)

    def __str__(self):
        return self.question


class Choice(models.Model):
    question = models.ForeignKey(
                Question, 
                related_name="choices", 
                on_delete = models.CASCADE)

    choice = models.CharField(max_length=50, blank=True)
    percentage = models.IntegerField(blank=False, default=0)

    def __str__(self):
        return self.choice + str(self.percentage)

main/forms.py
from django import forms
from .models import Uimg, Choice, Question

CHOICES = (('item_key1', 'Item title 1.1'),
          ('item_key2', 'Item title 1.2'),
          ('item_key3', 'Item title 1.3'),
          ('item_key4', 'Item title 1.4'),
          ('item_key5', 'Item title 1.5'))

class UimgForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField(max_length = 200)
    designation = forms.CharField(required=False) 
    company_name = forms.CharField(required=False)
    commitment = forms.CharField(required=False)

    img = forms.ImageField()
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    qustion_1 = forms.ChoiceField(choices=CHOICES, 
        widget=forms.RadioSelect(), required=False, 
        label='Are you aware on how to evaluate the startup on these checklist points ?')

    def __init__(self, *args, **kwargs):
        super(UimgForm, self).__init__(*args, **kwargs)
        self.fields['img'].label = "Upload a Photo"
        self.fields['commitment'].label = "Your commit statement"

class QuizForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        choice_list = tuple((x.percentage, x.choice ) for x in Choice.objects.filter(question=question).all())
        self.fields["answer"] = forms.ChoiceField(choices=choice_list, widget=forms.RadioSelect(), 
                                                    required=False, 
                                                    label=question.question)

class BaseQuizFormSet(forms.BaseFormSet):
    def get_form_kwargs(self, index):
        kwargs = super().get_form_kwargs(index)
        q = kwargs['questions'][index]
        return {'question': q}



main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Design Your Unicorn</title>

  <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' rel='stylesheet'>
  <link href='' rel='stylesheet'>
  <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
            

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/4a711e00ee.js" crossorigin="anonymous"></script>

  <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'main/assets/css/style.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;800&display=swap" rel="stylesheet">
</head>


<body>
  <!-- header section -->
  <section id="header">
    <div class="container">
      <img src="{% static 'main/assets/img/logo.jpg' %}" height="100px" alt="">
      <a class="btn-lg btn-primary header-btn ms-auto" href="#row2" role="button">{{ campaign.button}}</a>
    </div>
  </section>

{% block content %}{% endblock %}


  <script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script> <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>

{% block js %}{% endblock %}

  <footer id="footer">
    <p class="footer-text">© 2021 DesignYourUnicorn.com
. All rights reserved</p>
  </footer>
</body>

main/templates/main/home.html
    {% extends "main/base.html" %}
    {% load static %}
    {% block content %}

  <!-- hero section -->
  <section id="hero" style="background-image: url('{{ home.background.url }}');">
    <div class="container">
      <h1 class="hero-heading">{{ home.title}}</h1>
      <p class="number-desc">{{ home.description}}</p>
      <p class="hero-heading-desc"></p>

    <div class="row">
     {% for i in campaign %}
        <div class="col-lg-4">
          <img src="{{ i.icon.url}}" alt="" class="icon-img">
          <h3 class="icon-heading">{{ i.title }}</h3>
          <p class="icon-desc">{{ i.description }}</p>
          <a href="{% url 'campaign' campaign_id=i.id %}" class="frame-link">{{ i.cta }}</a>
        </div>
      {% endfor %}
      </div>
    </div>
  </section>
{% comment %} 
  <!-- Row 2 -->
  <section id="row2">
    <div class="container">
      <h1 class="join-heading">Make A Commitment To Yourself</h1>
      <p class="join-desc">Select the frame and create your custom image to share with the world.</p>
      <div class="row">

 {% for i in frames %}
        <div class="col-lg-6">
          <img src="{{ i.frame.url }}" alt="" width="100%" class="frame-img">
          <h2 class="frame-heading">{{ i.frame_heading }}</h2>
          <p class="frame-desc">{{ i.frame_desc }}</p>
          <a href="{% url 'upload' i.id i.campaign.id %}" class="frame-link">Commitment</a>
        </div>
{% endfor %}

      </div>
    </div>
  </section> {% endcomment %}

{% endblock content %}

main/templates/main/merged.html
<!DOCTYPE html>
<html lang="en">
<head>	
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pillow</title>

</head>
<body>
<h1>{{image2}}</h1>
{{merged_file_url}}
<img href="{{merged_file_url}}">

<h1>frame: {{frame}}</h1>
<br>
<h1>user img: {{user_img}}</h1>
</body>
</html>

main/templates/main/simple_upload.html
    {% extends "main/base.html" %}

    {% block content %}

        <!-- FORM TO UPLOAD THE IMAGES -->
        <form method="post" enctype="multipart/form-data" id="formUpload">
          {% csrf_token %}
          {{ form }}
        </form>

        <!-- MODAL TO CROP THE IMAGE -->
        <div class="modal fade" id="modalCrop">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
              </div>
              <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
              </div>
              <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                  <button type="button" class="btn btn-default js-zoom-in">
                    <span class="glyphicon glyphicon-zoom-in"></span>
                  </button>
                  <button type="button" class="btn btn-default js-zoom-out">
                    <span class="glyphicon glyphicon-zoom-out"></span>
                  </button>
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
              </div>
            </div>
          </div>
        </div>

        <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
        <h3> Selected frame </h3>
          {% if frame_img %}
            <img height="100%" src="{{ frame_img.frame.url }}">
          {% endif %}

        <h3> User Image </h3>
          {% if instance %}
            <img height="100%" src="{{ instance.img.url }}">
          {% endif %}
        <br>

        <h3> Merged Image </h3>
          {% if instance %}
            <img height="100%" src="{{ f_instance.m_img.url }}">
          {% endif %}
        <br>

    {% endblock content %}

    {% block js %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_img").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 173,
          minCropBoxHeight: 198,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      // Enable zoom in button
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      // Enable zoom out button
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });


      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

main/templates/main/upload.html
    {% extends "main/base.html" %}
    {% load crispy_forms_tags %}
    {% block content %}
    {% load static %}

    {% if img_data %}
    
  <section id="hero">
    <div class="container">
      <h1 style="color: black;">Your commitment certificate is here, Download and share with the world.</h1>
    </div>
  </section> 

    <div class="container">
              <div class="col-md-4 col-sm-6">
                    <div class="box14">
                        <img src="{{ img_data }}" alt="">
                    </div><br>
                    <div class="row">
                      <div class="col-md-12 col-sm-12 col-12">
                        <a href="{{ img_data }}" download="myphoto">
                        <button type="button" class="btn btn-primary btn-block download">
                        <i class="fa fa-download" aria-hidden="true"></i> Download
                        </button>
                        </a>
                      </div>
                    </div>
                </div>
                  <script>
                  function download(url, filename) {
                  fetch(url).then(function(t) {
                      return t.blob().then((b)=>{
                          var a = document.createElement("a");
                          a.href = URL.createObjectURL(b);
                          a.setAttribute("download", filename);
                          a.click();
                      }
                      );
                  });
                  }
                  </script>
    </div>
<!-- 
    <div class="container mt-40">
          <div class="row mt-30">
              <div class="col-md-4 col-sm-6">
                    <div class="box14">
                        <img src="{{ img_data }}" alt="">
                    </div>
                    <div class="row">

                      <div class="col-md-12 col-sm-12 col-12">
                        <a href="{{ img_data }}" download="myphoto">
                        <button type="button" class="btn btn-primary btn-block download"> 
                        <i class="fa fa-download" aria-hidden="true"></i> Download
                        </button>
                        </a>
                      </div>

                      <div class="col-md-12 col-sm-12 col-12">
                        <a href="{% url 'home' %}">
                        <button style="margin-top: 1rem;" type="button" class="btn btn-primary btn-block download"> 
                        <i class="fa fa-external-link" aria-hidden="true"></i>Invite your friend to Make commitment
                        </button>
                        </a>
                      </div>
                    </div>
                </div>

                  <script>
                  function download(url, filename) {
                  fetch(url).then(function(t) {
                      return t.blob().then((b)=>{
                          var a = document.createElement("a");
                          a.href = URL.createObjectURL(b);
                          a.setAttribute("download", filename);
                          a.click();
                      }
                      );
                  });
                  }
                  </script>
            </div>
        </div> -->
          
          {% else %}

  <!-- hero section -->
  <section id="hero" style="background-image: url('{{ campaign.background.url }}');">
    <div class="container">
      <h1 class="hero-heading">{{ campaign.title}}</h1>
      <p class="hero-heading-desc">{{ campaign.description}}</p>
  </section>

<!-- MultiStep Form -->

<link href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/smart_wizard.min.css" rel="stylesheet" type="text/css" />
<link href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/smart_wizard_theme_dots.min.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/jquery.smartWizard.min.js"></script>

    <div class="container">
    <!-- Modal -->

        <div class="modal-dialog modal-lg modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div id="smartwizard">
                        <ul>
                            <li><a href="#step-1">1<br /><small></small></a></li>
                            <li><a href="#step-2">2<br /><small></small></a></li>
                        </ul>
                    <div>    

                    <div id="step-1">
                      <form method="post" enctype="multipart/form-data" id="formUpload">
                        {% csrf_token %}
                        {{ form.name|as_crispy_field }}
                        {{ form.email|as_crispy_field }}
                        {{ form.designation|as_crispy_field }}
                        {{ form.company_name|as_crispy_field }}
                    </div>
                    <div id="step-2">
                        {{ form.commitment|as_crispy_field }}  
                        {{ form.img|as_crispy_field }}
                        {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}   
                      </form> 

                    </div>
                </div>
              </div>
        </div>
     </div>

<script type='text/javascript' src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'></script>

<script type='text/javascript'>$(document).ready(function(){

$('#smartwizard').smartWizard({
selected: 0,
theme: 'dots',
autoAdjustHeight:true,
transitionEffect:'fade',
showStepURLhash: false,
});
});</script>

<!-- /.MultiStep Form -->

<!-- <div class="container">

          <div class="register-photo">
              <div class="form-container">
                  <form method="post" enctype="multipart/form-data" id="formUpload">
                  {% csrf_token %}
                  {{ form|crispy }}
                  </form>
              </div>
          </div>

        <div class="container">
          <div class="row">
          <div class="col-md-4 col-sm-4 col-12"></div>
                      <div class="col-md-4 col-sm-4 col-12">
                        <a href="{% url 'home' %}">
                        <button type="button" class="btn btn-secondary btn-block"> 
                        <i class="fa fa-external-link" aria-hidden="true"> </i> Change
                        </button>
                        </a>
                      </div>
           <div class="col-md-4 col-sm-4 col-12"></div>
          </div>
          {% endif %}

</div> -->

        <!-- MODAL TO CROP THE IMAGE -->
        <div class="modal fade" id="modalCrop">
          <div class="modal-dialog">
            <div class="modal-content">
              <!---<div class="modal-header">
                <h4 class="modal-title">Crop the photo</h4>
              </div>-->
              <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
              </div>
              <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                  <button type="button" class="btn btn-default js-zoom-in">
                    <span class="glyphicon glyphicon-zoom-in"></span>
                  </button>
                  <button type="button" class="btn btn-default js-zoom-out">
                    <span class="glyphicon glyphicon-zoom-out"></span>
                  </button>
                </div>
                <button type="button" class="btn btn-primary btn-block download js-crop-and-upload"> 
                        <i class="fa fa-upload" aria-hidden="true"> </i> Upload
                </button>
              </div>
            </div>
          </div>
        </div>

<!--<div class="container">
         CONTAINER TO DISPLAY THE CROPPED IMAGES 
        <h3> Selected frame </h3>
          {% if frame_img %}
            <img height="500px" src="{{ frame_img.frame.url }}">
          {% endif %}

        <h3> User Image </h3>
          {% if instance %}
            <img height="500px" src="{{ instance.img.url }}">
          {% endif %}
        <br>

        <h3> Merged Image </h3>
          {% if instance %}
            <img height="500px" src="{{ f_instance.m_img.url }}">
          {% endif %}
        <br>
</div> -->
    {% endblock content %}

    {% block js %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_img").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      // Enable zoom in button
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      // Enable zoom out button
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });


      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>

{% endblock %}